# Generated by Django 5.1.4 on 2025-01-14 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=255, unique=True)),
                ('bank_type', models.CharField(max_length=100)),
                ('bank_number', models.CharField(max_length=20)),
                ('parents_monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('documents', models.FileField(blank=True, null=True, upload_to='applications_documents/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aid Application',
                'verbose_name_plural': 'Aid Applications',
            },
        ),
    ]
