# Generated by Django 5.1.4 on 2025-01-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0002_aidapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AidApplication',
        ),
    ]
