# Generated by Django 5.1.4 on 2025-01-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0004_aidapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidapplication',
            name='id',
        ),
        migrations.AlterField(
            model_name='aidapplication',
            name='application_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
