# Generated by Django 5.1.4 on 2025-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0005_remove_aidapplication_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidapplication',
            name='support_document',
            field=models.FileField(blank=True, null=True, upload_to='support_documents/'),
        ),
    ]
