# Generated by Django 5.1.4 on 2025-01-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0006_alter_aidapplication_support_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidapplication',
            name='application_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
