# Generated by Django 5.1.4 on 2025-01-24 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0009_alter_feedback_options_remove_feedback_date_modified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disburse_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund', to=settings.AUTH_USER_MODEL)),
                ('related_aid_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UAMS_App.aidapplication')),
            ],
        ),
    ]
