# Generated by Django 5.1.4 on 2025-01-24 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0010_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UAMS_App.fund'),
        ),
    ]
