# Generated by Django 5.1.4 on 2025-01-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0012_fund_disburse_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_fund',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
