# Generated by Django 5.1.4 on 2025-01-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0013_remove_notification_related_fund_delete_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('aid_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='UAMS_App.aidapplication')),
            ],
        ),
    ]
