# Generated by Django 5.1.4 on 2025-01-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0015_notification_related_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_fund',
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
