# Generated by Django 5.1.4 on 2025-01-25 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0016_remove_notification_related_fund_delete_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed')], default='pending', max_length=10)),
                ('aid_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund', to='UAMS_App.aidapplication')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='related_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UAMS_App.fund'),
        ),
    ]
