# Generated by Django 5.1.4 on 2025-01-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0017_fund_notification_related_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_aid_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UAMS_App.aidapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UAMS_App.feedback'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UAMS_App.fund'),
        ),
    ]
