# Generated by Django 5.1.4 on 2025-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0018_alter_notification_related_aid_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='duration_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
    ]
