# Generated by Django 5.1.4 on 2025-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0019_fund_duration_years_alter_fund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
