# Generated by Django 5.1.4 on 2025-01-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0020_alter_feedback_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
