# Generated by Django 5.1.5 on 2025-01-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0021_alter_aidapplication_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('mail', 'Mail Only'), ('system', 'System Notifications Only'), ('both', 'Both Mail and System Notifications')], default='mail', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
