# Generated by Django 5.1.5 on 2025-02-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UAMS_App', '0022_notificationpreference_alter_fund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='preference',
            field=models.CharField(choices=[('mail', 'Mail Only'), ('system', 'System Notifications Only'), ('both', 'Both Mail and System Notifications')], default='system', max_length=10),
        ),
    ]
